=== s31688/zdaj-se-pjatk-data/schemas/subject-override.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1659129904.json",
  "title": "Root",
  "type": "object",
  "required": ["data", "updatedAt"],
  "properties": {
    "title": {
      "$id": "#root/title",
      "title": "Title",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": ""
    },
    "data": {
      "$id": "#root/data",
      "title": "Data",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/data/items",
        "title": "Items",
        "type": "object",
        "properties": {
          "question": {
            "$id": "#root/data/items/question",
            "title": "Question",
            "type": "string",
            "default": ""
          },
          "id": {
            "$id": "#root/data/items/id",
            "title": "Id",
            "type": "integer",
            "default": 0
          },
          "numberOfComments": {
            "$id": "#root/data/items/numberOfComments",
            "title": "Numberofcomments",
            "type": "integer",
            "default": 0
          },
          "answers": {
            "$id": "#root/data/items/answers",
            "title": "Answers",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/data/items/answers/items",
              "title": "Items",
              "type": "object",
              "required": ["answer", "correct"],
              "properties": {
                "answer": {
                  "$id": "#root/data/items/answers/items/answer",
                  "title": "Answer",
                  "type": "string",
                  "default": ""
                },
                "correct": {
                  "$id": "#root/data/items/answers/items/correct",
                  "title": "Correct",
                  "type": "boolean",
                  "default": true
                }
              }
            }
          },
          "comments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "author": {
                  "type": "string"
                },
                "comment": {
                  "type": "string"
                },
                "date": {
                  "type": "string",
                  "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
                }
              },
              "required": ["author", "comment", "date"]
            }
          },
          "contributors": {
            "$id": "#root/data/items/contributors",
            "title": "Contributors",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "updatedAt": {
      "$id": "#root/updatedAt",
      "title": "Updatedat",
      "type": "integer",
      "default": 0
    }
  }
}

=== s31688/zdaj-se-pjatk-data/modeling_and_analysis_of_it_systems.json
{
  "$schema": "schemas/subject.json",
  "title": "Modeling and Analysis of IT Systems",
  "id": "modeling_and_analysis_of_it_systems",
  "data": [
    {
      "question": "Assosiations can be directly implemented in Java",
      "id": 3628,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Associations from the object model are implemented as tables in the relational mode",
      "id": 3629,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Directional associations are always more useful than bidirectional associations",
      "id": 3630,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": false
        },
        {
          "answer": "No",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "An association is a group of connections within the same semantics and structure",
      "id": 3631,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Yes",
          "correct": true
        },
        {
          "answer": "No",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}

=== s31688/zdaj-se-pjatk-data/zpr.json
{
  "$schema": "schemas/subject.json",
  "title": "Zarządzanie projektem informatycznym (ZPR)",
  "id": "zpr",
  "data": [
    {
      "question": "<span>Która z cech nie jest charakterystyczna dla typowej działalności projektowej</span>",
      "id": 3192,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>zespołowość</span>",
          "correct": false
        },
        {
          "answer": "<span>planowanie</span>",
          "correct": false
        },
        {
          "answer": "<span>dążenie do przewidywalnego rezultatu</span>",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Które z określeń nie jest charakterystyczne dla działalności projektowe. Projekt jest</span>",
      "id": 3288,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>ukierunkowany na wytworzenie unikalnego produktu</span>",
          "correct": false
        },
        {
          "answer": "zawsze działalnością krytyczną dla przedsiębiorstwa",
          "correct": true
        },
        {
          "answer": "<span>działalnością czasową</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Wskaż zdania prawdziwe</span>",
      "id": 3289,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Na grafie precedensji nie można przedstawić zależności typu FS i FF między zadaniami",
          "correct": false
        },
        {
          "answer": "Graf precedensji przedstawia strukturę zadaniowo-czasową projektu",
          "correct": true
        },
        {
          "answer": "Zawsze dla diagramu Gantta można wykonać odpowiadający mu graf precedensji",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Twórcą map myśli jest",
      "id": 3290,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Covey",
          "correct": false
        },
        {
          "answer": "Eisenhauer",
          "correct": false
        },
        {
          "answer": "Buzan",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Jesteś kierownikiem projektu informatycznego. Twój kierownik ds. jakości poinformował Cię, że należy zakończyć planowanie testów oprogramowania tuż przed ich rozpoczęciem. Jednocześnie powinieneś rozpocząć testowanie produktów możliwie jak najpóźniej, aby uwzględnić wszystkie zmiany w nich zachodzące. Jaka wobec tego powinna by zależność między aktywnością polegającą na planowaniu testów a aktywnością polegającą na ich wykonaniu</span><em><span><br></span></em>",
      "id": 3291,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "FS",
          "correct": true
        },
        {
          "answer": "SF",
          "correct": false
        },
        {
          "answer": "SS",
          "correct": false
        },
        {
          "answer": "FF",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Które ze stwierdzeń dotyczących struktury podziału prac jest prawdziwe",
      "id": 3292,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "WBS przedstawia wszystkie zadania, które muszą by wykonane w projekcie",
          "correct": true
        },
        {
          "answer": "każdy element WBS reprezentuje cechę produktu projektu",
          "correct": false
        },
        {
          "answer": "WBS przedstawia pakiety prac uporządkowane w postaci liniowej, niestrukturalizowanej listy",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Który z obszarów klasyfikacyjnych ryzyka jest obszarem stosowanym w taksonomiach ryzyka projektów informatycznych",
      "id": 3293,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "założeń opłacalności",
          "correct": true
        },
        {
          "answer": "zewnętrznych zależności",
          "correct": true
        },
        {
          "answer": "techniczny",
          "correct": true
        },
        {
          "answer": "organizacyjny, planowania",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Procesy zarządzania projektem zdefiniowanie niezgodnie z PMBOK, to",
      "id": 3294,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "inicjacji, planowania, kontrolne, wykonawcze, testowania, końcowe",
          "correct": true
        },
        {
          "answer": "inicjacji, planowania, kontrolne, wykonawcze, końcowe",
          "correct": true
        },
        {
          "answer": "planowania, kontrolne, wykonawcze, końcowe",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}

=== s31688/zdaj-se-pjatk-data/skj.json
{
  "$schema": "schemas/subject.json",
  "title": "Sieci Komputerowe - ang - egzamin ",
  "id": "skj",
  "data": [
    {
      "question": "<span>TEMPEST protects against:</span>",
      "id": 2628,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>sniffing at link layer&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>sniffing at physical layer</span>",
          "correct": false
        },
        {
          "answer": "<span>spoofing at physical layer</span>",
          "correct": false
        },
        {
          "answer": "<span>TEMPEST is not a protection technology</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Processing a recursive DNS query, a contacted DNS server is responsible for providing the answer for the client. It may be necessary that the server communicates with other servers to get the asnwer.</span>",
      "id": 2629,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>No</span>",
          "correct": false
        },
        {
          "answer": "Yes",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;A protocol used to automatically configure IP networking for a host is called:</span>",
      "id": 2630,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>DNS&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>DHCP</span>",
          "correct": false
        },
        {
          "answer": "<span>SNMP</span>",
          "correct": false
        },
        {
          "answer": "<span>DHCM&nbsp;</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>If on one link, at the same time, in the same place and on the same frequency, multiple devices communicate, than what is the type of multiplexing used? Choose the acronym.</span>",
      "id": 2631,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>FDM</span>",
          "correct": false
        },
        {
          "answer": "<span>TDM&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>CDM</span>",
          "correct": true
        },
        {
          "answer": "<span>WDM</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "IPSec provides security in layer",
      "id": 2632,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "transport",
          "correct": false
        },
        {
          "answer": "network",
          "correct": true
        },
        {
          "answer": "application",
          "correct": false
        },
        {
          "answer": "link",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;How many bits are used in an IPv6 address</span>",
      "id": 2633,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>1024</span>",
          "correct": false
        },
        {
          "answer": "<span>128&nbsp;</span>",
          "correct": true
        },
        {
          "answer": "<span>64</span>",
          "correct": false
        },
        {
          "answer": "<span>256&nbsp;</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>&nbsp;Window mechanism is used in</span>",
      "id": 2634,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>TCP</span>",
          "correct": true
        },
        {
          "answer": "<span>OSPF</span>",
          "correct": false
        },
        {
          "answer": "<span>IP&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>UDP</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>Internet telephony usually uses</span>",
      "id": 2635,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>HTTP</span>",
          "correct": false
        },
        {
          "answer": "<span>UDP</span>",
          "correct": true
        },
        {
          "answer": "<span>TCP</span>",
          "correct": false
        },
        {
          "answer": "<span>IPvoice</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>What services does an IP network offer for applications?&nbsp;</span>",
      "id": 2636,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>an unreliable \"best-effort\" service</span>",
          "correct": true
        },
        {
          "answer": "<span>a communication service with guaranteed minimal throughput</span>",
          "correct": false
        },
        {
          "answer": "<span>a reliable TCP service</span>",
          "correct": false
        },
        {
          "answer": "<span>a communication service with guaranteed upper bounds on delay</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span>In the physical layer we are talking about (…)</span>",
      "id": 2637,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>frames&nbsp;</span>",
          "correct": false
        },
        {
          "answer": "<span>bits</span>",
          "correct": true
        },
        {
          "answer": "<span>segments&nbsp;</span><br><br>",
          "correct": false
        },
        {
          "answer": "packets",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "PGP używa kluczy:",
      "id": 2642,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "kluczy Geanta",
          "correct": false
        },
        {
          "answer": "żadna z pozostałych odpowiedzi nie jest poprawna",
          "correct": true
        },
        {
          "answer": "symetrycznych",
          "correct": false
        },
        {
          "answer": "jednokrotnych",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Co opisuje uzycie gniazd przez serwer w niezawodnej, połączeniowej komunikacji z klientem?",
      "id": 2643,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "gniazdo serwera rozpoczyna połączenie",
          "correct": false
        },
        {
          "answer": "serwer oczekuje połączeń od klientów",
          "correct": true
        },
        {
          "answer": "gniazdo klienta musi istnieć przed gniazdem serwera",
          "correct": false
        },
        {
          "answer": "port jednoznacznie determinuje gniazdo serwera",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Uwierzytelnianie ma na celu:",
      "id": 2644,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "potwierdzenie wiarygodności uzytkownika",
          "correct": false
        },
        {
          "answer": "sprawdzenie integralności przesyłanego komunikatu",
          "correct": false
        },
        {
          "answer": "sprawdzenie uprawnień użytkownika",
          "correct": false
        },
        {
          "answer": "sprawdzenie tożsamości użytkownika",
          "correct": true
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}

=== s31688/zdaj-se-pjatk-data/mad.json
{
  "$schema": "schemas/subject.json",
  "title": "Matematyka Dyskretna 2020",
  "id": "mad",
  "data": [
    {
      "question": "Jeżeli wiemy, że maszyna kapsułkująca podczas jednego cyklu produkcyjnego zacina się z prawdopodobieństwem 0.1, a w przeciągu dnia uruchamiamy 10 cykli produkcyjnych, to prawdą jest to, że:",
      "id": 3340,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Spodziewamy się jednego zacięcia",
          "correct": false
        },
        {
          "answer": "Spodziewamy się pierwszego zacięcia dopiero w ostatnim cyklu danego dnia",
          "correct": false
        },
        {
          "answer": "Spodziewamy się pięciu zacięć",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Na ile sposobów możemy rozdać 5 różnych książek trójce dzieci, tak aby każde z nich dostało co najmniej jedną książkę:",
      "id": 3341,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "3!*S(5,3)",
          "correct": false
        },
        {
          "answer": "2!*S(5,2)",
          "correct": false
        },
        {
          "answer": "5!*S(3,2)",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Zbiorem potęgowym zbioru {<span>∅</span>} jest:",
      "id": 3342,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "{<span>∅</span>,{<span>∅</span>}}",
          "correct": true
        },
        {
          "answer": "{<span>∅</span>}",
          "correct": false
        },
        {
          "answer": "{{<span>∅</span>}}",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Które z poniższych zbiorów są równoliczne z zbiorem liczb naturalnych:",
      "id": 3343,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "R",
          "correct": false
        },
        {
          "answer": "Zbiór liczb pierwszych",
          "correct": false
        },
        {
          "answer": "{1,5,2,6}",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Jeżeli nieprawdą jest że wszyscy wysocy ludzię są inteligentni to wiemy, że prawdą jest:",
      "id": 3344,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Niscy ludzie są inteligentni",
          "correct": false
        },
        {
          "answer": "Wysocy ludzie nie są inteligentni",
          "correct": false
        },
        {
          "answer": "Wzrost nie pozwala na jednoznaczne wnioskowanie o inteligencji",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Iluzjonista wydobył z pięciu różnych cylindrów pięć różnych przedmiotów. Po prezentacji włożył je losowo po jednym do cylindra. Na ile sposobów mógł to zrobić, jeśli żaden przedmiot nie trafił do cylindra w którym był?",
      "id": 3345,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "196",
          "correct": false
        },
        {
          "answer": "25",
          "correct": false
        },
        {
          "answer": "55",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Do zdań, dla których do określenia wartości wystarczy analiza syntaksuczna należą",
      "id": 3346,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Zdania złożone",
          "correct": false
        },
        {
          "answer": "Zdania sprzeczne",
          "correct": false
        },
        {
          "answer": "Zdania proste",
          "correct": false
        },
        {
          "answer": "Zadne&nbsp;",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Wariancja zmiennej losowej zawsze",
      "id": 3382,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "jest dodatnia,",
          "correct": false
        },
        {
          "answer": "należy do zakresu [0,1],",
          "correct": false
        },
        {
          "answer": "jest nieujemna.",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Liczba podzbiorów zbioru {A,B,C,D,E} o parzystej liczbie elementów jest:",
      "id": 3383,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "równa 16",
          "correct": false
        },
        {
          "answer": "parzysta",
          "correct": true
        },
        {
          "answer": "równa 20",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Relacja określona następująco: R = { (x,y)&nbsp;<span>∈</span>&nbsp;R x R: ( x*y = 1) } jest",
      "id": 3384,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "funkcją częściową",
          "correct": true
        },
        {
          "answer": "asymetryczna",
          "correct": true
        },
        {
          "answer": "funkcja całkowitą",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}

=== s31688/zdaj-se-pjatk-data/hur.json
{
  "$schema": "schemas/subject.json",
  "title": "Hurtownie danych i aplikacje OLAP",
  "id": "hur",
  "data": [
    {
      "question": "Różnica impedancji",
      "id": 2983,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "To obciążenie systemowe związane z wykonywaniem kodu SQL i próba pominięcia go lub zastąpienia w operacjach bazodanowych",
          "correct": false
        },
        {
          "answer": "To obciążenie systemowe powstające, gdy wykonany zostaje kod SQL zaszyty w kodzie napisanym w języku obiektowym",
          "correct": false
        },
        {
          "answer": "To dysonans między \"światem obiektowym\" a \"światem relacyjnym\"",
          "correct": true
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}

=== s31688/zdaj-se-pjatk-data/ppb_ang.json
{
  "$schema": "schemas/subject.json",
  "title": "Legal foundations of business",
  "id": "ppb_ang",
  "data": [
    {
      "question": "<span id=\"docs-internal-guid-8ca4b00f-4cd4-3829-b960-3409447a70e3\">According to the Civil Code, a statement by the other party willing to conclude an agreement that defines the essential provisions of this contract is</span><p></p>\n<p>&nbsp;\n          </p>",
      "id": 3082,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<p id=\"docs-internal-guid-cc7a22f2-4cdc-f585-aa13-524f498d3ef2\" dir=\"ltr\"><span>invitation to prognosis</span></p>",
          "correct": false
        },
        {
          "answer": "<p id=\"docs-internal-guid-3ba8f0cf-4cdd-170d-e5da-92110544eb03\" dir=\"ltr\"><span>invitation to negotiate</span></p>",
          "correct": false
        },
        {
          "answer": "<span id=\"docs-internal-guid-06afe752-4cdd-302f-d668-81a4bdaba049\">offer</span>",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "<p dir=\"ltr\"><span>According to the Civil Code, the contract for impossible provision</span></p>",
      "id": 3083,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<p dir=\"ltr\"><span>Is important but does not produce legal effects until the service becomes possible</span></p>",
          "correct": false
        },
        {
          "answer": "<p dir=\"ltr\"><span>Is not valid</span></p>",
          "correct": true
        },
        {
          "answer": "<p dir=\"ltr\"><span>Is valid, but the provision for the impossible provision is considered non-reserved</span></p>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<p dir=\"ltr\"><span>Word markings, which refers directly or indirectly to the name of a place, town, region, or country that identifies a product as originating from this site is</span></p>",
      "id": 3084,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<p dir=\"ltr\"><span>Trademark</span></p>",
          "correct": false
        },
        {
          "answer": "<p dir=\"ltr\"><span>Geographical indication</span></p>",
          "correct": true
        },
        {
          "answer": "<p dir=\"ltr\"><span>Topography of integrated circuit systems</span></p>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<ol id=\"docs-internal-guid-6c216dd6-4cdf-666e-8431-34adc88d9ba2\">\n<li dir=\"ltr\">\n<p dir=\"ltr\"><span>According to the Civil Code, the installment sale is made in the scope of the company’s activity of selling a moving item to an individual for a price paid in specified installments, if the contract is to be issued to buyer according to the contract.</span></p>\n</li>\n</ol>",
      "id": 3085,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<p id=\"docs-internal-guid-218584b2-4cdf-747b-4e07-95e5d010ebd7\" dir=\"ltr\"><span>after full payment</span></p>",
          "correct": true
        },
        {
          "answer": "<p id=\"docs-internal-guid-93775569-4cdf-a00f-a01c-d518e1a9cda5\" dir=\"ltr\"><span>after paying half of the price</span></p>",
          "correct": false
        },
        {
          "answer": "<p id=\"docs-internal-guid-5f61968a-4cdf-8f44-9c44-fa917391ad3b\" dir=\"ltr\"><span>before full payment</span></p>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<p dir=\"ltr\"><span>Kajetan B. does not want to buy a horse, but he wants to own one, he will pay for the blacksmith, fodder, veterinarians and other things necessary for the animal. What agreement do we have to use in this situation?</span></p>",
      "id": 3086,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<p id=\"docs-internal-guid-57935077-4ce0-5f8b-4ed6-318ad04c7e2c\" dir=\"ltr\"><span>lease</span></p>",
          "correct": true
        },
        {
          "answer": "<p id=\"docs-internal-guid-fe934787-4ce0-6bb5-857a-c978d8ef689b\" dir=\"ltr\"><span>sale</span></p>",
          "correct": false
        },
        {
          "answer": "<p id=\"docs-internal-guid-75897332-4ce0-778e-a676-e5f4749048ad\" dir=\"ltr\"><span>rent</span></p>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "<span id=\"docs-internal-guid-c7e107b5-4cd3-177e-fba8-4eb2c17fc59e\">Antonina has just graduated from a reputable university. She has a great idea for a business. She has sufficient knowledge and would like to expand her business. Unfortunately, her idea requires a big startup capital. Antonina managed to persuade her uncle to declare that he could provide the capital but because of his work he did not want to get involved in the company’s current business. For the above situation match the appropriate organisational and legal form</span>",
      "id": 3081,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span id=\"docs-internal-guid-6fe6b1f1-4cd3-47f7-c4fa-dc153fbad44d\">Ltd company</span><span><br class=\"kix-line-break\"></span>",
          "correct": true
        },
        {
          "answer": "<span id=\"docs-internal-guid-dc13e31a-4cd3-3840-d313-4728d6efd1f4\">limited partnership </span><span><br class=\"kix-line-break\"></span>",
          "correct": false
        },
        {
          "answer": "partnership company<p></p>\n<p>&nbsp;</p>",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}
