=== s31688/zdaj-se-pjatk-data/schemas/subject-override.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1659129904.json",
  "title": "Root",
  "type": "object",
  "required": ["data", "updatedAt"],
  "properties": {
    "title": {
      "$id": "#root/title",
      "title": "Title",
      "type": "string",
      "default": ""
    },
    "id": {
      "$id": "#root/id",
      "title": "Id",
      "type": "string",
      "default": ""
    },
    "data": {
      "$id": "#root/data",
      "title": "Data",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/data/items",
        "title": "Items",
        "type": "object",
        "properties": {
          "question": {
            "$id": "#root/data/items/question",
            "title": "Question",
            "type": "string",
            "default": ""
          },
          "id": {
            "$id": "#root/data/items/id",
            "title": "Id",
            "type": "integer",
            "default": 0
          },
          "numberOfComments": {
            "$id": "#root/data/items/numberOfComments",
            "title": "Numberofcomments",
            "type": "integer",
            "default": 0
          },
          "answers": {
            "$id": "#root/data/items/answers",
            "title": "Answers",
            "type": "array",
            "default": [],
            "items": {
              "$id": "#root/data/items/answers/items",
              "title": "Items",
              "type": "object",
              "required": ["answer", "correct"],
              "properties": {
                "answer": {
                  "$id": "#root/data/items/answers/items/answer",
                  "title": "Answer",
                  "type": "string",
                  "default": ""
                },
                "correct": {
                  "$id": "#root/data/items/answers/items/correct",
                  "title": "Correct",
                  "type": "boolean",
                  "default": true
                }
              }
            }
          },
          "comments": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "author": {
                  "type": "string"
                },
                "comment": {
                  "type": "string"
                },
                "date": {
                  "type": "string",
                  "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4} [0-9]{2}:[0-9]{2}:[0-9]{2}$"
                }
              },
              "required": ["author", "comment", "date"]
            }
          },
          "contributors": {
            "$id": "#root/data/items/contributors",
            "title": "Contributors",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "updatedAt": {
      "$id": "#root/updatedAt",
      "title": "Updatedat",
      "type": "integer",
      "default": 0
    }
  }
}

=== s31688/zdaj-se-pjatk-data/aug.json
{
  "$schema": "schemas/subject.json",
  "title": "Automaty i Gramatyki",
  "id": "aug",
  "data": [
    {
      "question": "<span>Dana jest relacja {(1,2),(2,3),(3,1),(2,4),(5,3)} określona na zbiorze {1,2,3,4,5,6}. Która z poniższych relacji stanowi jej&nbsp;</span><strong>domknięcie symetryczne</strong><span>?</span>",
      "id": 3088,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "<span>{(1,2), (1,3), (2,1), (2,3), (2,4), (3,2), (3,5), (4,2)}</span>",
          "correct": false
        },
        {
          "answer": "<span>{(1,1), (1,2), (2,1), (2,3), (2,5), (3,1), (3,2), (3,5), (4,2), (5,3)}</span>",
          "correct": false
        },
        {
          "answer": "<span>{(1,2), (1,3), (2,1), (2,3), (2,4), (3,1), (3,2), (3,5), (4,2), (5,3)}</span>",
          "correct": true
        },
        {
          "answer": "<span>{(1,2), (1,3), (2,3), (2,4), (3,1), (3,2), (3,5), (5,3)}</span>",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Czy dane stwierdzenie jest prawdziwe?",
      "id": 3476,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Determinizacja automatu skończonego może spowodować wykładniczą eksplozję liczby stanów.",
          "correct": true
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym prowadzi do automatu równoważnego automatowi wejściowemu.",
          "correct": true
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym może zmienić język akceptowany przez automat.",
          "correct": false
        },
        {
          "answer": "Eliminacja ε-przejść w automacie skończonym nie powoduje wzrostu liczby jego stanów.",
          "correct": false
        }
      ],
      "comments": []
    },
    {
      "question": "Czy dane stwierdzenie jest prawdziwe?",
      "id": 3477,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Lex/Flex generuje rodzaj automatu stosowego.",
          "correct": false
        },
        {
          "answer": "Zadaniem skanera jest podział tekstu wejściowego na leksemy.",
          "correct": true
        },
        {
          "answer": "Lex/Flex służy do tworzenia analizatorów leksykalnych (skanerów).",
          "correct": true
        },
        {
          "answer": "Lex/Flex generuje rodzaj automatu skończonego.",
          "correct": true
        }
      ],
      "comments": []
    },
    {
      "question": "Dana jest następująca gramatyka:<p></p>\n<p>S → aXS | bYS | ε<br>X → aXX | b<br>Y → bYY | a</p>\n<p>Język generowany przez tą gramatykę to:\n          </p>",
      "id": 3478,
      "numberOfComments": 0,
      "answers": [
        {
          "answer": "Słowa zawierające tyle samo liter a i b",
          "correct": true
        },
        {
          "answer": "Słowa zawierające więcej liter a niż b",
          "correct": false
        },
        {
          "answer": "Pusty język",
          "correct": false
        },
        {
          "answer": "Palindromy nad alfabetem {a,b}",
          "correct": false
        }
      ],
      "comments": []
    }
  ],
  "updatedAt": 1705528642695
}
